import ciw
import AS_setting
import numpy as np

# first simulation (from ambulance post to scene address)
# unit = person per hour
# 'class KUNINGAN':  [ciw.dists.NoArrivals(),
#                                                 ciw.dists.Exponential(0.054),
#                                                 ciw.dists.NoArrivals()],
#                             'class REMPOA': [ciw.dists.NoArrivals(),
#                                              ciw.dists.NoArrivals(),
#                                              ciw.dists.Exponential(0.08)]

N = ciw.create_network(
    arrival_distributions={
        'Class 0': [ciw.dists.Exponential(0.049),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals()],
        'Class 1': [ciw.dists.NoArrivals(),
                    ciw.dists.Exponential(0.054),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals()],
        'Class 2': [ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.Exponential(0.08),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals(),
                    ciw.dists.NoArrivals()]
    },
    service_distributions={
        # HI ambulance
        'Class 0': [ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(1),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(0.67),
                    ciw.dists.Exponential(1.58),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(2),
                    ciw.dists.Exponential(5),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(1.89),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(4),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(4),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(2),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(2),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(2),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(3.83),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(3),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(0.57),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(1.96),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(1),
                    ciw.dists.Exponential(4.32),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(2.31),
                    ciw.dists.Exponential(4.28),
                    ciw.dists.Deterministic(0.0)],
        # KUNINGAN ambulance
        'Class 1': [ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(1.71),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(1),
                    ciw.dists.Exponential(1.09),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(1.33),
                    ciw.dists.Exponential(30),
                    ciw.dists.Exponential(1.2),
                    ciw.dists.Exponential(0.8),
                    ciw.dists.Exponential(12),
                    ciw.dists.Exponential(1.71),
                    ciw.dists.Exponential(0.70),
                    ciw.dists.Exponential(2.4),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(12),
                    ciw.dists.Exponential(1),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(1.33),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(1.05),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(12),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(1.15),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(0.46),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(1.64),
                    ciw.dists.Exponential(0.92),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(1.67),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(4.8),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(2.82),
                    ciw.dists.Exponential(2.5),
                    ciw.dists.Deterministic(0.0)],
        # REMPOA ambulane
        'Class 2': [ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(1.33),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(2),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(0.57),
                    ciw.dists.Exponential(2.76),
                    ciw.dists.Exponential(2.20),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(4.05),
                    ciw.dists.Exponential(2.4),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(1.05),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(1.28),
                    ciw.dists.Exponential(2.07),
                    ciw.dists.Exponential(1.09),
                    ciw.dists.Exponential(2.20),
                    ciw.dists.Exponential(2.20),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(1),
                    ciw.dists.Exponential(1.4),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(2),
                    ciw.dists.Exponential(1.18),
                    ciw.dists.Exponential(3),
                    ciw.dists.Exponential(1.09),
                    ciw.dists.Exponential(1.66),
                    ciw.dists.Exponential(1.71),
                    ciw.dists.Exponential(2),
                    ciw.dists.Exponential(0.8),
                    ciw.dists.Exponential(2),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(0.81),
                    ciw.dists.Exponential(1.67),
                    ciw.dists.Exponential(2.14),
                    ciw.dists.Exponential(0.8),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(2.6),
                    ciw.dists.Exponential(1.63),
                    ciw.dists.Exponential(2),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(1.38),
                    ciw.dists.Exponential(1.24),
                    ciw.dists.Exponential(1.17),
                    ciw.dists.Exponential(1.03),
                    ciw.dists.Exponential(0.29),
                    ciw.dists.Exponential(2.4),
                    ciw.dists.Deterministic(0.0),
                    ciw.dists.Exponential(2.55)]
    },
    routing={'Class 0': AS_setting.HI,
             'Class 1': AS_setting.KUNINGAN,
             'Class 2': AS_setting.REMPOA},
    # according to the table, HI ambulances were used in 35 rescues,
    # KUNINGAN ambulances were used in 36 rescues, and REMPOA ambulances were used in 130 rescues.
    number_of_servers=[35, 36, 130]+[0 for _ in range(53)]
)

average_waits_HI = []
for trial in range(10):
    ciw.seed(trial)
    Q = ciw.Simulation(N)
    Q.simulate_until_max_time(200)
    recs = Q.get_all_records()
    waits1 = [r.waiting_time for r in recs if r.node == 1]
    average_waits_HI.append(sum(waits1) / len(waits1))

A_HI = sum(average_waits_HI) / len(average_waits_HI)
print(A_HI)
